// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flsdeadqtrxnemggnelx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsc2RlYWRxdHJ4bmVtZ2duZWx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NDc0NTAsImV4cCI6MjA1ODEyMzQ1MH0.274qapCv0dubdNtdS-gFmteyRQjr1Sw1_rkopda9VeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);